// import '/public/assets/css/animate.min.css'
// import '/public/assets/css/bootstrap.min.css'
// import '/public/assets/css/flaticon.min.css'
// import '/public/assets/css/flaticon_ygency.css'
// import '/public/assets/css/fontawesome-5.14.0.min.css'
// import '/public/assets/css/magnific-popup.min.css'
// import '/public/assets/css/nice-select.min.css'
// import '/public/assets/css/slick.min.css'
// import '/public/assets/css/style.css'
// import '/public/assets/css/flaticon_ygency.css.map'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import '@/app/(app)/globals.css'
import Provider from '@/trpc/Provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' className='dark'>
      <head>
        <meta charSet='utf-8' />
        <meta name='description' />
        <meta httpEquiv='X-UA-Compatible' content='IE=edge' />
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1, shrink-to-fit=no'
        />
        {/* Title */}
        <title>Ygency - Web Agency React NextJS Template</title>
        {/* Favicon Icon */}
        <link
          rel='shortcut icon'
          href='assets/images/favicon.png'
          type='image/x-icon'
        />
        {/* Google Fonts */}
        {/* eslint-disable-next-line @next/next/no-page-custom-font */}
        <link
          href='https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap'
          rel='stylesheet'
        />
        {/* Flaticon */}
        {/* eslint-disable-next-line @next/next/no-css-tags */}
        <link rel='stylesheet' href='assets/css/flaticon.min.css' />
        {/* eslint-disable-next-line @next/next/no-css-tags */}
        <link rel='stylesheet' href='assets/css/fontawesome-5.14.0.min.css' />
        {/* eslint-disable-next-line @next/next/no-css-tags */}
        <link rel='stylesheet' href='assets/css/bootstrap.min.css' />
        {/* eslint-disable-next-line @next/next/no-css-tags */}
        <link rel='stylesheet' href='assets/css/magnific-popup.min.css' />
        {/* eslint-disable-next-line @next/next/no-css-tags */}
        <link rel='stylesheet' href='assets/css/nice-select.min.css' />
        {/* eslint-disable-next-line @next/next/no-css-tags */}
        <link rel='stylesheet' href='assets/css/animate.min.css' />
        {/* eslint-disable-next-line @next/next/no-css-tags */}
        <link rel='stylesheet' href='assets/css/slick.min.css' />
        {/* eslint-disable-next-line @next/next/no-css-tags */}
        <link rel='stylesheet' href='assets/css/style.css' />
      </head>
      <body className={`${inter.className} dark:bg-[#0f162b]`}>
        <Provider>{children}</Provider>
      </body>
    </html>
  )
}
